docs:
  - '**/*.md'
site:
  - 'pages/**'
workflows:
  - '.github/workflows/**'
  - '.github/labeler.yml'
# Automatically label bot PRs for merge
automerge:
  - any: ['**/*']
    createdBy: ['dependabot[bot]', 'github-actions[bot]', 'clarity[bot]']