[CmdletBinding()]
param(
  [string]$RepoRoot=".",
  [switch]$AutoRestore
)
$ErrorActionPreference='Continue'

$memPath = Join-Path $RepoRoot "Cody's Memory.yaml"
function Is-Yaml-Good([string]$p){
  try { $raw=Get-Content -Raw -Path $p -ErrorAction Stop; $null=ConvertFrom-Yaml -Yaml $raw -AllDocuments; return $true } catch { return $false }
}

if (Is-Yaml-Good $memPath) { Write-Host "Memory is valid."; exit 0 }

# Save broken copy
$histDir = Join-Path $RepoRoot "memory-history"
New-Item -ItemType Directory -Force -Path $histDir | Out-Null
if (Test-Path $memPath) {
  $stamp = (Get-Date -Format 'yyyyMMddTHHmmssZ')
  Copy-Item -Path $memPath -Destination (Join-Path $histDir "$stamp-BROKEN-Codys-Memory.yaml") -Force
}

# Try restore from newest good snapshot
$snaps = @(Get-ChildItem $histDir -Filter "*Codys-Memory.yaml" -File | Sort-Object LastWriteTime -Descending)
foreach ($s in $snaps) {
  if (Is-Yaml-Good $s.FullName) {
    Copy-Item -Path $s.FullName -Destination $memPath -Force
    Write-Host "Restored Memory from snapshot: $($s.Name)"
    exit 0
  }
}

# Fallback: write a minimal, valid baseline (safe defaults)
$baseline = @"
meta:
  project: Avalon
  file_name: "Cody's Memory.yaml"
  version: "BASE-RECOVERY"
  last_updated: "$(Get-Date).ToUniversalTime().ToString("o")"
  author: "Cody (GPT-5 Pro)"
  notes: >
    Auto-recovery baseline generated by normalize-memory.ps1 after parse failure.
system: { os: "Windows 11", device: "Gaming PC", only_windows: true }
hosting: { frontend_domain: "fairiesofavalon.com", pwa_app_shell: true, pages_root: "pages", microapps_path: "pages/apps", custom_domain_cname: true, cdn_imports: ["three","three/addons/","@pixiv/three-vrm"] }
avatars_present: ["Abbey","Alexandria","Billie","Carol","Charlotte","Clarice","Jem","Nina","Odessa","Reyczar","Sorcha","Themis","WhiteStar","Tracy","Stella"]
runtime: { paths: { queue_requests: "requests", queue_processed: "processed", progress_file: "pages/apps/overseers/progress.json" } }
"@
Set-Content -Path $memPath -Value $baseline -Encoding utf8NoBOM
Write-Host "Wrote baseline Memory (recovery)."
exit 0
