param(
  [Parameter()][object]$WorldCount = 3,
  [Parameter()][object]$NonInteractive = $false
)
Import-Module -Name (Join-Path $PSScriptRoot 'AsInt.psm1')
$wc = As-Int -Value $WorldCount
$nonInt = $false
try { $nonInt = [bool]$NonInteractive } catch { $nonInt = $false }
$Root = Split-Path -Parent $PSScriptRoot
$Pages = Join-Path $Root 'pages'
$Apps  = Join-Path $Pages 'apps'
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'alexandria/worlds') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'tracy/artboards') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'overseers') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'charlotte/pipelines') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'charlotte/voiceovers') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'carol/plans') -Force
$null = New-Item -ItemType Directory -Path (Join-Path $Apps 'jem/programs') -Force
$now = (Get-Date).ToUniversalTime().ToString("s") + "Z"
function Write-JsonFile { param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][object]$Object) $json = $Object | ConvertTo-Json -Depth 10; [System.IO.File]::WriteAllText($Path, $json, [System.Text.Encoding]::UTF8) }
$worldsPath = Join-Path $Apps 'alexandria/worlds'
$items = @()
for ($i = 1; $i -le $wc; $i++) {
  $slug = "auto-" + $i
  $id = "world-" + $slug
  $file = "world-" + $slug + ".json"
  $world = @{ id = $id; title = "Auto World #" + $i; summary = "Generated by Run-All"; lore = "A placeholder world generated locally to keep the UI alive."; seedPrompts = @("Sketch a small map and three landmarks.","Name two notable NPCs and their quirks."); created = $now; version = "1.0.0" }
  Write-JsonFile -Path (Join-Path $worldsPath $file) -Object $world
  $items += @{ id = $id; slug = $slug; title = $world.title; summary = $world.summary; file = $file }
}
Write-JsonFile -Path (Join-Path $worldsPath 'index.json') -Object @{ updated = $now; items = $items }
Write-JsonFile -Path (Join-Path $Apps 'tracy/artboards/index.json') -Object @{ updated = $now; items = @(@{ id="art-" + [guid]::NewGuid().ToString("N").Substring(0,6); title="Idea Board"; status="draft"; prompt="High-level artboard for the homepage hero." }) }
Write-JsonFile -Path (Join-Path $Apps 'overseers/vrm-index.json') -Object @{ updated = $now; avatars = @(@{ id="vrm-alexandria"; name="Alexandria"; uri="vrm/alexandria.vrm" }, @{ id="vrm-charlotte"; name="Charlotte"; uri="vrm/charlotte.vrm" }) }
Write-JsonFile -Path (Join-Path $Apps 'charlotte/pipelines/index.json') -Object @{ updated = $now; pipelines = @(@{ id="welcome"; text="Welcome to Avalon. Build the AI and let them build the site."; voice="en-US-AriaNeural"; format="riff-16khz-16bit-mono-pcm" }) }
$voiceIndex = Join-Path $Apps 'charlotte/voiceovers/index.json'
if (-not (Test-Path $voiceIndex)) { Write-JsonFile -Path $voiceIndex -Object @{ updated = $now; items = @() } }
Write-JsonFile -Path (Join-Path $Apps 'carol/plans/index.json') -Object @{ updated = $now; plans = @(@{ id="site-v1"; title="Site v1"; tasks=@("Wire homepage hero","Hook up Actions CTAs","Publish via GitHub Pages") }) }
Write-JsonFile -Path (Join-Path $Apps 'jem/programs/index.json') -Object @{ updated = $now; programs = @(@{ id="healthcheck"; title="Health Check"; type="script"; entry="scripts/Run-All.ps1" }) }
Write-Host "Run-All completed: generated content under pages/apps/**"
