$root=Split-Path -Parent $PSScriptRoot
$src = Join-Path $root 'asset/textures/wallpapers'
$cssOut = Join-Path $root 'pages/apps/tracy/skins/avalon-skin.css'
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $cssOut) | Out-Null
$files = @()
if (Test-Path $src) {
  $files = Get-ChildItem -Path $src -File -Include *.jpg,*.jpeg,*.png | Sort-Object LastWriteTime -Descending
}
function PickByKeyword($kw) { foreach($f in $files){ if ($f.Name -match $kw) { return $f } } return ($files | Select-Object -First 1) }
$map = @{
  hero = "castle|palace|forest|avalon|island|sky|mountain|lake|shore"
  alexandria = "library|books|gothic|study|desk"
  charlotte  = "tower|relay|screens|control|tech"
  nina       = "lab|futuristic|white|blue|neon|sci"
  tracy      = "studio|cathedral|art|canvas|brush"
  carol      = "kitchen|restaurant|table|food"
  jem        = "dojo|gym|training|tatami|martial"
  stella     = "observatory|stars|night|meditation|cosmos"
  sorcha     = "mansion|social|pool|party|glam"
  odessa     = "museum|armor|asian|samurai"
  billie     = "glitz|gold|mansion|luxury"
  themis     = "record|hall|statue|scroll"
  abbey      = "vault|gold|bank|ledger"
  clarice    = "court|judge|palace|columns|marble"
  overseers  = "palace|castle|throne"
}
$sel = @{}
foreach($k in $map.Keys){ $sel[$k] = PickByKeyword($map[$k]) }
$hero = if($sel.hero){$sel.hero.Name}else{""}
function N($x){ if($x){ return $x.Name } else { return "" } }
$css = @"
/* Generated by Tracy-Skin-From-Wallpapers.ps1 */
:root{
  --hero-bg: url('/asset/textures/wallpapers/$hero');
  --room-alexandria-bg: url('/asset/textures/wallpapers/$(N $sel.alexandria)');
  --room-charlotte-bg:  url('/asset/textures/wallpapers/$(N $sel.charlotte)');
  --room-nina-bg:       url('/asset/textures/wallpapers/$(N $sel.nina)');
  --room-tracy-bg:      url('/asset/textures/wallpapers/$(N $sel.tracy)');
  --room-carol-bg:      url('/asset/textures/wallpapers/$(N $sel.carol)');
  --room-jem-bg:        url('/asset/textures/wallpapers/$(N $sel.jem)');
  --room-stella-bg:     url('/asset/textures/wallpapers/$(N $sel.stella)');
  --room-sorcha-bg:     url('/asset/textures/wallpapers/$(N $sel.sorcha)');
  --room-odessa-bg:     url('/asset/textures/wallpapers/$(N $sel.odessa)');
  --room-billie-bg:     url('/asset/textures/wallpapers/$(N $sel.billie)');
  --room-themis-bg:     url('/asset/textures/wallpapers/$(N $sel.themis)');
  --room-abbey-bg:      url('/asset/textures/wallpapers/$(N $sel.abbey)');
  --room-clarice-bg:    url('/asset/textures/wallpapers/$(N $sel.clarice)');
  --room-overseers-bg:  url('/asset/textures/wallpapers/$(N $sel.overseers)');
}
.hero{background-image: var(--hero-bg); background-size:cover; background-position:center; background-repeat:no-repeat; min-height:38vh; border-radius:12px; border:1px solid #172033}
.room-bg{ background-size:cover; background-position:center; background-repeat:no-repeat; border-radius:12px; border:1px solid #172033; min-height:30vh }
.room-bg.alexandria{background-image: var(--room-alexandria-bg)}
.room-bg.charlotte{background-image: var(--room-charlotte-bg)}
.room-bg.nina{background-image: var(--room-nina-bg)}
.room-bg.tracy{background-image: var(--room-tracy-bg)}
.room-bg.carol{background-image: var(--room-carol-bg)}
.room-bg.jem{background-image: var(--room-jem-bg)}
.room-bg.stella{background-image: var(--room-stella-bg)}
.room-bg.sorcha{background-image: var(--room-sorcha-bg)}
.room-bg.odessa{background-image: var(--room-odessa-bg)}
.room-bg.billie{background-image: var(--room-billie-bg)}
.room-bg.themis{background-image: var(--room-themis-bg)}
.room-bg.abbey{background-image: var(--room-abbey-bg)}
.room-bg.clarice{background-image: var(--room-clarice-bg)}
.room-bg.overseers{background-image: var(--room-overseers-bg)}
"@
[IO.File]::WriteAllText($cssOut, $css, [Text.Encoding]::UTF8)
Write-Host "Skin -> $cssOut"
