$root=Split-Path -Parent $PSScriptRoot
$wall=Join-Path $root 'asset/textures/wallpapers'
$outDir=Join-Path $root 'pages/apps/tracy/skins'; New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$css=@"/* Auto-generated by Tracy from wallpapers */
:root{--bg:#0b0f17;--ink:#e5e7eb}
.wallpaper-hero{min-height:32vh;background-size:cover;background-position:center;border-radius:12px;margin:12px 0;border:1px solid #172033}
"@
$i=0
if(Test-Path $wall){
  Get-ChildItem -Path $wall -File -Include *.jpg,*.jpeg,*.png | Sort-Object Name | ForEach-Object {
    $name = $_.FullName.Replace($root,"").Replace("\","/").TrimStart("/")
    $cls  = "hero-"+$i
    $css += "."+$cls+"{background-image:url('/"+$name+"');}\n"
    $i++
  }
}
Set-Content -Path (Join-Path $outDir 'avalon-skin.css') -Value $css -Encoding UTF8
Write-Host "Skin generated with $i wallpapers."
