name: Auto approve &amp; merge

on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  statuses: read

jobs:
  automerge:
    if: >
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Wait for status checks
        uses: actions/github-script@v7
        with:
          script: |
            // Intentionally left empty.  The merge step will only run once checks are green.
      - name: Auto approve safe changes
        if: >
          contains(github.event.pull_request.labels.*.name, 'site') ||
          contains(github.event.pull_request.labels.*.name, 'docs') ||
          contains(github.event.pull_request.labels.*.name, 'workflows') ||
          contains(github.event.pull_request.labels.*.name, 'automerge')
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: "true"
          MERGE_BLOCK_LABELS: hold