name: Deploy — GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "pages/**"
      - "asset/**"
      - "app.js"
      - "sw.js"
      - "manifest.webmanifest"
      - "CNAME"
      - ".nojekyll"
      - ".github/workflows/deploy-pages.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure CNAME file exists
        run: |
          if [ ! -f CNAME ]; then
            echo "fairiesofavalon.com" > CNAME
          fi
          cat CNAME

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
