# Only update the "paths:" section if you want automatic deploys on CSS change.
# Add "app.css" to the list:
paths:
  - "index.html"
  - "app.css"
  - "pages/**"
  - "asset/**"
  - "app.js"
  - "sw.js"
  - "manifest.webmanifest"
  - "CNAME"
  - ".nojekyll"
  - ".github/workflows/deploy-pages.yml"
