name: Deploy — GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - "pages/**"
      - "CNAME"
      - "asset/textures/wallpapers/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact (copy CNAME + wallpapers)
        run: |
          mkdir -p pages
          cp CNAME pages/CNAME || true

          # Copy wallpapers if present (supports your folder)
          if [ -d "asset/textures/wallpapers" ]; then
            mkdir -p pages/wallpapers
            cp -r asset/textures/wallpapers/* pages/wallpapers/ || true
          fi

          # Build wallpapers index.json (safe if folder missing/empty)
          node -e "const fs=require('fs');const p='pages/wallpapers';try{fs.mkdirSync(p,{recursive:true});const list=fs.readdirSync(p).filter(f=>/\.(png|jpe?g|webp)$/i.test(f)).sort();fs.writeFileSync(p+'/index.json',JSON.stringify(list));}catch(e){/* no-op */}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "pages"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          cname: fairiesofavalon.com
