name: Overseers — AI Core

on:
  workflow_dispatch:
  push:
    paths:
      - "permissions/**"
      - "scripts/overseers/**"
      - "Cody's Memory.yaml"
      - "pages/**"
      - "asset/**"
      - ".github/workflows/**"

permissions:
  contents: write

jobs:
  process-permissions:
    if: ${{ !contains(github.event.head_commit.message, '[skip ai-core]') }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run permissions + progress processor
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./scripts/overseers/process-permissions.ps1

      - name: Commit state.json + progress.json
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/apps/overseers/permissions/state.json pages/apps/overseers/progress.json permissions/processed || true
          git commit -m "Overseers: update permissions state & progress [skip ai-core]" || echo "Nothing to commit"
          git push
