name: Overseers — AI Core

on:
  workflow_dispatch:
  push:
    paths:
      - "permissions/**"
      - "scripts/overseers/**"

permissions:
  contents: write

jobs:
  process-permissions:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run permissions processor
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./scripts/overseers/process-permissions.ps1

      - name: Commit state.json
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/apps/overseers/permissions/state.json permissions/processed || true
          git commit -m "Overseers: update permissions state" || echo "Nothing to commit"
          git push
