name: Queue — Full Roster
on: { workflow_dispatch: {} }
permissions: { contents: write }
jobs:
  seed:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - name: Seed queue from Memory (no wings manifest)
        shell: pwsh
        run: pwsh -File "apps/overseers/ai/seed-queue.ps1"
      - name: Commit queued tasks
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then echo "No changes"; else git commit -m "Queue: seed full roster"; git push; fi
