name: Queue — Full Roster

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  seed:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Seed queue from Memory build order
        shell: pwsh
        run: |
          $Root  = (Get-Location).Path
          $Queue = Join-Path $Root 'apps\overseers\queue'
          New-Item -ItemType Directory -Force -Path $Queue | Out-Null

          $memPath = Join-Path $Root "Cody's Memory.yaml"
          $mem = Get-Content -Raw -LiteralPath $memPath -Encoding UTF8 | ConvertFrom-Yaml
          $ids = $mem.build_order_initial
          if (-not $ids) { throw "No build_order_initial in Memory." }

          $i = 1
          foreach ($id in $ids) {
            $task = @{
              id       = "scaffold:$id"
              type     = "scaffold_fairy"
              fairy_id = "$id"
              created  = (Get-Date).ToString('s') + 'Z'
              status   = "queued"
            } | ConvertTo-Json -Depth 6
            $file = ("{0:D3}_{1}.json" -f $i, $id)
            Set-Content -LiteralPath (Join-Path $Queue $file) -Encoding UTF8 -NoNewline -Value $task
            $i++
          }

          # Also ensure models manifest will be generated
          $mf = @{
            id      = "write_models_manifest"
            type    = "write_models_manifest"
            created = (Get-Date).ToString('s') + 'Z'
            status  = "queued"
          } | ConvertTo-Json -Depth 6
          Set-Content -LiteralPath (Join-Path $Queue ('{0:D3}_models_manifest.json' -f $i)) -Encoding UTF8 -NoNewline -Value $mf

      - name: Commit queued tasks
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Queue: seed full roster scaffold tasks"
            git push
          fi
