name: Runner — Process Overseers Queue

on:
  push:
    branches: [ main ]
    paths:
      - "apps/overseers/queue/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-queue:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Run Queue Runner
        shell: pwsh
        run: pwsh -File "apps/overseers/ai/queue-runner.ps1"

      - name: Commit generated files
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Queue Runner: processed tasks (fairy scaffolds, interfaces, manifests)"
            git push
          fi

      - name: Upload runner artifacts
        uses: actions/upload-artifact@v4
        with:
          name: queue-runner-out
          path: |
            apps/overseers/out/*
            apps/overseers/log/*
          if-no-files-found: warn
          retention-days: 7
